### ISSUE TITLE
Error: NativeScript debugger was not able to get inspector socket port.

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-vscode-extension#188]
When I try to debug with VSCode for iOS on emulator, I get the following error:

> [NSDebugAdapter] Ready to attach to application on /var/folders/8g/y0qh4rsj05x9fml7snq4_9g91zr2y0/T/11858-16790-appah0.bpf0t.sock
> Suppressing debugging client.
> [NSDebugAdapter] Connection to target application established on /var/folders/8g/y0qh4rsj05x9fml7snq4_9g91zr2y0/T/11858-16790-appah0.bpf0t.sock
> [NSDebugAdapter] Connection to target application successfully enabled
> Frontend client connected.
> Error: NativeScript debugger was not able to get inspector socket port.
>     at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
>     at IOSDebugService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:232:30)
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:4:58)
>     at <anonymous>
> [NSDebugAdapter] The tns command finished its execution with code 120.

I'm testing with:
- VSCode 1.24.0
- {N} CLI: 4.1.0
- {N} iOS Runtime: 4.1.0

**Comment by vedranstanic82** [comment]
Same here.

**Comment by drmistral** [comment]
Same here, restarting it sometimes works, sometimes don't.

> Error: NativeScript debugger was not able to get inspector socket port.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at IOSDebugService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:232:30)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:4:58)
[NSDebugAdapter] The tns command finished its execution with code 120.

**Comment by shabib3** [comment]
Same here

**Comment by Ross-Jo** [comment]
Hope this error be fixed soon~!

**Comment by ADjenkov** [comment]
The problem can be reproduced with this application https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-6011

**Comment by howieluo** [comment]
I think that the attach can work well.

**Comment by howieluo** [comment]
I think the it should be a side effect of {N} CLI: 4.1.0. And, it should be fixed with https://github.com/NativeScript/nativescript-cli/commit/55b5813c7837200c624ff634ec57f3c0e343bd3f#diff-3ea8e9be6fce663fc286a4462786a297. 
Maybe we can wait for another release of {N} CLI.

**Comment by VladimirAmiorkov** [comment]
Still happens with `tns --version`  4.2.0

**Comment by howieluo** [comment]
I think that it should emit a new event like "readyForOpeneInspector" in the function "configureReadyEvent" which is raised until waiting for "NativeScript debugger has opened inspector socket on port ...".

**Comment by rosen-vladimirov** [comment]
Hey guys,
Can you please try the latest CLI's rc version. You can install it by executing:
```
npm i -g nativescript@rc
```

We've applied several fixes that should resolve this issue.

**Comment by nickcabral** [comment]
@rosen-vladimirov great suggestion! **Setting `--timeout 60` fixes the issue for me**. To answer your last question, I was seeing the issue on a simulator. I haven't recently tried to debug on a device.

Do you think increasing the timeout is the actual solution, or is it a workaround for an underlying issue? (Since I didn't need it until recently) In any case, I'll provide the timeout arg for the time being, so thank you for the idea!

**Comment by larssn** [comment]
@rosen-vladimirov I can confirm that the problem still happens with 4.2.3.

**Comment by nickcabral** [comment]
I previously posted that I was able to workaround this by passing the —timeout arg, but I was wrong as the problem still occurs regularly. I can confirm it still exists with NS v5. 

It’s a pretty major issue. JS development is tedious without a working debugger. Any ETA on a fix?

**Comment by mspusta78** [comment]
Same issue here. I updated to v5 hoping it would allow attach to debugger but still keep getting
Unable to apply changes on device: B556BF08-1C56-4B2E-93B9-209ACB8E851F. 
Error is: Unable to find free local port..

**Comment by lohiarahul** [comment]
I have been facing massive problems with this. Every-time the socket error occurs, I have to restart the Simulator. Stop the 'tns run' execution and do it all over again. Now the debugger is detached even when I make a change and save. It has become impossible to debug.

**Comment by tmay57** [comment]
I recently installed Visual Studio Code and the NativeScript extension. I'm getting this inspector port error - Consistently All The Time. Is there any new information or a workaround for this problem? 

I'm evaluating the toolchain for a project and don't consider the toolchain usable without basic debugging, so this is a showstopper for the Visual Studio Code NativeScript extension combo.

I've tried using SideKick and that seems to work better in someways. However, I'd like to get the Visual Studio Code extension working.

Output:
Project successfully built.
Installing on device ---------------------...
Successfully installed on device with identifier '-----------------'.
Successfully transferred all files on device ------------.
Refreshing application on device ----------------...
Setting up debugger proxy...
Press Ctrl + C to terminate, or disconnect.
Opened localhost 41000
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:41000
Successfully synced application org.nativescript.MyApp02 on device ------------.
[NSDebugAdapter] Ready to attach to application on 41000
Frontend client connected.
NativeScript debugger was not able to get inspector socket port on device --------------- for application org.nativescript.MyApp02.
Cannot connect to device socket. The error message is 'Device socket port cannot be found.'.

**Comment by mrpaaske** [comment]
Same problem here as well..
```
tns --version
5.1.1
```

**Comment by DimitarTachev** [comment]
Hi guys,

Sorry for the late response. Most probably you are getting this error because your app is not able to finish it's bootstrapping for 10 seconds. It's easy to reproduce this by executing some slow operations in your app starting point. 

It seems that the `--timeout` flag is not respected for this specific timeout and we increased it to 60 seconds in the latest CLI release candidate (currently available as `nativescript@rc` and most probably will be released as `nativescript@5.2.1` in a couple of days).

You could also try passing the `--debug-brk` flag to the CLI as a workaround. In this way, only the Native App will be started and the runtime will stop for debugging before starting the NativeScript app (the 10 seconds timeout should be enough in this case). In order to achieve this in VSCode, you can extend your configurations in `.vscode/launch.json` e.g.:
```
"name": "Launch on iOS",
...
"tnsArgs": [
   "--debugBrk"
]
```

Using `--debug-brk` you will  also be able to debug the above-mentioned application start logic.

**Comment by mrwrighty** [comment]
Still a big problem in Sidekick 1.16.2-v.2019.3.12.12. and Nativescript 5.2.3.

Since upgrading both to the latest I am unable to load the debugger at any time. Sidekick returns Cannot start debug session. Error: Device socket port cannot be found.

**Comment by mrwrighty** [comment]
Update:-

After multiple attempts the debugger finally connected, but very hit and miss at around 10% success rate.

**Comment by BeehiveHRMS** [comment]
tns --version 6.7.4

<private> adding listener `<private>` for service: iMessage
<private> creating monitor for service: iMessage
<private> updating availability for FTCServiceTypeiMessage   => from FTCServiceAvailabilityUnavailable to FTCServiceAvailabilityAvailable
CONSOLE INFO file: node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
NativeScript debugger has opened inspector socket on port 18183 for com.app.beehivehrms.
Successfully synced application com.app.beehivehrms on device 5BC65979-5A29-45B9-BFAF-70D50D59CA65.
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:1:0: Loading inspector modules...
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:6:0: Finished loading inspector modules.
NativeScript debugger attached.
CONSOLE LOG file: node_modules/@nativescript/core/ui/frame/frame-common.js:581:0: topmost() is deprecated. Use Frame.topmost() instead.
NativeScript debugger was not able to get inspector socket port on device 496cb96d36469201e1e68de921a06c473h63eb7a for application com.app.hrms

these msg come and it crashes in iphone 6

**Comment by jpcarnes** [comment]
@mrwrighty I am running into the exact same issue what did your solution end up being? Cheers

**Comment by hraynaud** [comment]
Also experiencing this issue. Any ideas. as of latest nativescript-cli version 7.0.11

**Comment by Maharshi020** [comment]
This issue is not resolved yet. When are you guys resolving this issue.

**Comment by elcreator** [comment]
same

**Comment by micahlt** [comment]
Same issue here.  This really isn't acceptable - it's almost impossible to build a whole application without a working debugger.

**Comment by dlcole** [comment]
I'm seeing the same issue with all versions of {N} 8.x on iOS emulators and devices.  Currently running 8.1.5 due to compatibility issues with 8.2.x.  Mine is a plain JavaScript project.

**Comment by chinnawip** [comment]
yes, same issue here too. Please help us. eating more my energy.
